language: c
sudo: required
dist: trusty
script:
 - cd ~/barrier-breaker
 - make defconfig
 - make


branches:
  only:
    - barrier-breaker

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install zlib-static
  - git clone git://git.openwrt.org/14.07/openwrt.git barrier-breaker
  - cd barrier-breaker
  - ./scripts/feeds update -a
  - cd package

  
addons:
  apt:
    packages:
    - libasound2-dev
    - libsoxr-dev
    - libpopt-dev
    - libssl-dev
    - libpolarssl-dev
    - libconfig-dev
    - libncurses5-dev
    - unzip
    - subversion
    - zlib1g-dev
    - zlib-static
    - gettext
