language: c
sudo: required
dist: trusty
script:
 - echo "Working directory is `pwd`"
 - echo "TRAVIS_BUILD_DIR is $TRAVIS_BUILD_DIR"
 - cd $TRAVIS_BUILD_DIR/sdk/barrier-breaker
 - ./scripts/feeds update -a
 - make defconfig
 - make

branches:
  only:
    - barrier-breaker

before_install:
  - mkdir -p $TRAVIS_BUILD_DIR/sdk ; cd $TRAVIS_BUILD_DIR/sdk
  - git clone git://git.openwrt.org/14.07/openwrt.git barrier-breaker

  
addons:
  apt:
    packages:
    - libssl-dev
    - libncurses5-dev
    - unzip
    - subversion
    - zlib1g-dev
    - gawk
    - gcc-multilib
    - flex
    - gettext
