language: c
sudo: required
dist: trusty

branches:
  only:
    - barrier-breaker

env:
  matrix:
    - SDK_URL=https://downloads.openwrt.org/barrier_breaker/14.07/ar71xx/generic/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2.tar.bz2

install:
 - mkdir -p $TRAVIS_BUILD_DIR/cache ; cd $TRAVIS_BUILD_DIR/cache
 - wget -c $SDK_URL
 - mkdir -p $TRAVIS_BUILD_DIR/sdk ; cd $TRAVIS_BUILD_DIR/sdk
 - export FILE=$TRAVIS_BUILD_DIR/cache/$(basename $SDK_URL)
 - file $FILE
 - tar xjf $FILE
 - cd $TRAVIS_BUILD_DIR/sdk/OpenWrt-SDK-*
 
script:
 - echo "Working directory is `pwd`"
 - echo "TRAVIS_BUILD_DIR is $TRAVIS_BUILD_DIR"
 - ./scripts/feeds update -a
 - make defconfig
 - make

addons:
  apt:
    packages:
    - libssl-dev
    - libncurses5-dev
    - unzip
    - subversion
    - zlib1g-dev
    - gawk
    - gcc-multilib
    - flex
    - gettext
